- main.go
I will change the default metrics path to be empty once this ends
> Add configurable path to dump metrics

- .github/workflows/gh-pages-deploy.yml
- .github/workflows/gh-pages.yml
- site/assets/index.html
it seems to work but there is a problem with CORS being disabled by default
> Deploy to gh-pages

- main.go
> Fix crash on empty proxylist

- README.md
- helm/.helmignore
- helm/Chart.yaml
- helm/README.md
- helm/templates/_helpers.tpl
- helm/templates/deployment.yaml
- helm/values.yaml
This is a helm chart for experienced users.
The app could be easily deployed to the Kubernetes cluster and it could be scaled to a thousand replicas just in one click
> Add helm chart for Kubernetes installation

- defaultconfig.go
- main.go
Moved out default config into a separate file and populated it with some targets
> Default config restructure

- .gitignore
- terraform/gcp_expressvpn/README.md
- terraform/gcp_expressvpn/main.tf
- terraform/gcp_expressvpn/variables.tf
For advanced users: Simple Terraform manifest for fast deploy VM into GCP using ExpressVPN
> terraform initial

- .github/workflows/release-docker.yaml
https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
https://github.com/Arriven/db1000n/issues/67
> Add multiarch build for Docker

- main.go
- site/assets/vpn.html
First time coding in go, so code may be horrible
Need to replace URL to correct one
closes #110
> Added country check to make sure users don't launch it with Ukrainian IPs

- scripts/StartDB1000N.bat
> Added comments to start script

- scripts/StartDB1000N.bat
> Added supervisor to start script

- docker-compose.yml
- docs/README.md
- docs/advanced-users-and-devs.md
- docs/docker-vpn.md
- kubernetes/helm-charts/values.yaml
- kubernetes/manifests/daemonset.yaml
- kubernetes/manifests/deployment.yaml
- terraform/aws_ec2/main.tf
- terraform/gcp_expressvpn/main.tf
> Update cloud defaults to point to advanced image

- src/metrics/metrics.go
- src/runner/runner.go
Accumulate traffic over time in metrics. Trying to calculate traffic per second without proper tooling was not a best idea
Fixes #182 
- [*] Bug fix (non-breaking change which fixes an issue)
Run the app with this change
* Release version: v0.5.14
* Platform: linux-amd64
> Accumulate traffic over time in metrics

- src/jobs/base.go
- src/jobs/http.go
- src/jobs/packetgen.go
- src/jobs/rawnet.go
- src/runner/runner.go
- src/utils/templates/templates.go
- testconfig.json
Added optional dynamic filter to jobs to be able to disable some jobs to some random clients to have more diverse traffic
> Dynamic job filtering

- docs/advanced-users-and-devs.md
Fixes https://github.com/Arriven/db1000n/issues/211
```text
admin@ip-XXX:~$ source <(curl https://raw.githubusercontent.com/Arriven/db1000n/main/install.sh)
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1691  100  1691    0     0   117k      0 --:--:-- --:--:-- --:--:--  117k
Downloading an archive...
Checking md5 hash...
db1000n
```
> use source for installation through script

- src/jobs/http.go
- src/jobs/rawnet.go
Template parsing is an expensive operation; now it happens on rawnet job init.
> Split template parsing and execution in rawnet; tidy up http job a bit

- src/jobs/http.go
Async mode in http job causes more problems than benefits. Bombardier and other tools use set amount of connections and this was already achievable long ago by setting "count" on a job
> remove async from http job (ineffective)

- README.md
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
add links to FB and insta
* Release version:
* Platform:
```text
logs
```
> add insta and fb

- go.mod
- go.sum
- main.go
- src/jobs/base.go
- src/jobs/dnsblast.go
- src/jobs/http.go
- src/jobs/packetgen.go
- src/jobs/rawnet.go
- src/jobs/slowloris.go
- src/packetgen/packetgen.go
- src/runner/config/config.go
- src/runner/runner.go
- testconfig.yaml
I want to add support for yaml based config to this app to support better templating. This is a first step. Still need to fix proxylist in http job and packetgen
> (WIP) Use mapstruct for job args where possible

- src/jobs/http.go
- src/utils/templates/templates.go
- testconfig.json
- testconfig.yaml
Fixed proxylist parsing
Fixes #243 
> Fix proxylist

- src/jobs/packetgen.go
- src/packetgen/packetgen.go
Make it possible to set parameters of raw network packetgen should use to send packets
> Expose network settings in packetgen

- src/jobs/packetgen.go
- src/packetgen/packetgen.go
- src/packetgen/utils.go
- src/utils/templates/templates.go
- testconfig.json
Expose packetgen.ResolveHost to the templating engine
* Release version: latest
* Platform: linux-amd64
> Expose ResolveHost to template engine

- main.go
- src/jobs/base.go
- src/jobs/dnsblast.go
- src/jobs/http.go
- src/jobs/packetgen.go
- src/jobs/rawnet.go
- src/jobs/slowloris.go
- src/runner/config/config.go
- src/runner/runner.go
Allow setting system proxy override
Alternative to #207 
> allow setting system proxy override

- src/jobs/base.go
- src/jobs/http.go
- src/jobs/packetgen.go
- src/packetgen/packetgen.go
- src/packetgen/utils.go
- testconfig.json
Split opening raw connection from sending packets in packetgen. Move metrics out of the package to the job. Minor linter fixes
- Platform:
```text
logs
```
> Minor packetgen improvements

- main.go
Add flag to enable pprof if needed
- Platform:
```text
logs
```
> Add flag to enable pprof

- .gitattributes
- .github/workflows/golangci-lint.yaml
- main.go
- src/metrics/prometheus.go
- src/runner/runner.go
- src/utils/crypto.go
Add golangci-lint action to automate linting and catch issues early
- Platform:
```text
logs
```
> Golangci lint

- src/jobs/http.go
- src/jobs/packetgen.go
- src/jobs/rawnet.go
- src/metrics/metrics.go
- src/runner/runner.go
```text
2022/03/09 17:55:20.121068 runner.go:162: Атака проводиться успішно! Руський воєнний корабль іди нахуй!
2022/03/09 17:55:20.121085 runner.go:163: Attack is successful! Russian warship, go fuck yourself!
2022/03/09 17:55:20.121093 runner.go:164: The app has generated approximately 1188 bytes of traffic
2022/03/09 17:55:20.121100 runner.go:166: Of which for 1056 bytes we received some response from the target
```
> More user friendly logs

- src/jobs/rawnet.go
forgot to include one more commit
> User friendly logs

- src/jobs/base.go
- src/jobs/complex.go
- src/jobs/dnsblast.go
- src/jobs/http.go
- src/jobs/packetgen.go
- src/jobs/rawnet.go
- src/jobs/slowloris.go
- src/runner/runner.go
- src/utils/templates/templates.go
- src/utils/utils.go
- testconfig.yaml
Adding jobs that would allow to create complex attack patterns
- Platform:
```text
logs
```
> Add complex job scenarios

- ota/README.md
fix markdown in ota readme
- Platform:
```text
logs
```
> fix ota readme markdown

- .github/workflows/ko-build.yaml
- .ko.yaml
Build and push docker images with ko
> Setup docker publish with ko

- src/jobs/base.go
- src/jobs/complex.go
- src/jobs/utils.go
- src/runner/runner.go
Added a job to simulate loops in scenarios
- Platform:
```text
logs
```
> Added loop job

- main.go
- src/core/packetgen/utils.go
- src/jobs/http.go
- src/jobs/rawnet.go
- src/runner/runner.go
Cleanup runner to use ctx instead of stop channel. Also some minor code cleanup
- Platform:
```text
logs
```
> use context in runner

- terraform/azure/variables.tf
- terraform/heroku/terraform.tfvars
This PR updates Terraform variables for Azure and Heroku.
Fixes #308.
- Release version: latest
- Platform: Azure
> Terraform variables update

- docker-compose.yml
Use Google DNS while performing DNS health check
Fixes https://github.com/Arriven/db1000n/issues/300#issuecomment-1065949528
> Update docker-compose.yml example

- main.go
- src/utils/ota/ota.go
- src/utils/ota/restart_darwin.go
- src/utils/ota/restart_linux.go
- src/utils/ota/restart_linux_test.go
Please do not accept PRs with nolint directives. Some are introduced simply because of lack of knowledge of [common golang wisdom](https://zchee.github.io/golang-wiki/CodeReviewComments/#indent-error-flow).
> Fix nolint directives

- src/jobs/rawnet.go
- testconfig.json
We were only sending one message per opened tcp connection
> Send multiple tcp messages in one conn

- .github/workflows/release-binaries.yaml
- install.sh
Add ARM build for old Raspberry Pi
```sh
root@0a48eb43fa67:/# uname -a
Linux 0a48eb43fa67 5.4.0-1050-raspi #56-Ubuntu SMP PREEMPT Thu Jan 13 13:15:17 UTC 2022 armv7l armv7l armv7l GNU/Linux
root@0a48eb43fa67:/# REPO=fpavlovskiy/db1000n ./install.sh 
Downloading an archive...
Checking md5 hash...
db1000n
Successfully installed db1000n
root@0a48eb43fa67:/# ./db1000n --help
2022/03/14 19:21:03.555136 main.go:54: DB1000n [Version: v0.0.1-dev][PID=2884]
Usage of ./db1000n:
-b string
raw backup config in case the primary one is unavailable (default "age-encryption.org/v1\n-> scrypt rlhhbQscLTHtMJnsVC8J3w 18\nbl+FTU88bICOcDdSkUZr0CICwF9WbLnVjRCsvDsZ89U\n--- 2d4Iu3+bHzaAhDq4ngGnDRZPSkLSZxmKDgJrQk1SR4s\n#\x01\x899\xa0\x012%\xae\xe1g\xc0\xec\xe8H\x12\xe0\ …
```
> Add ARM build

- docs/faq.md
- src/utils/ota/README.md
Hi, I was just reading docs and found some typo issues).
- Platform:
```text
no logs
```
> docs: fix some typos

- main.go
- src/jobs/base.go
- src/jobs/utils.go
- src/runner/config/config.go
- src/utils/utils.go
- testconfig.json
Add functionality to encrypt only specific jobs. Also add a flag to skip encrypted jobs if someone is very concerned about their security
WIP #343 
- Platform:
```text
logs
```
> Encrypt specific jobs

- main.go
- src/jobs/base.go
- src/jobs/complex.go
- src/jobs/dnsblast.go
- src/jobs/http.go
- src/jobs/packetgen.go
- src/jobs/rawnet.go
- src/jobs/slowloris.go
- src/jobs/utils.go
- src/runner/runner.go
disabling logs in encrypted jobs (still need to disable logging in slowloris and dnsblast modules)
- Platform:
```text
logs
```
> disable logging in encrypted jobs

- src/utils/crypto.go
decryption takes a bunch of RAM to generate scrypt identity. we don't do decryption in hot paths so it's better to only allow one thread doing decryption at a time to avoid OOM
Fixes #347 
- Platform:
```text
logs
```
> only allow one thread to decrypt data at a time

- main.go
- src/core/dnsblast/dns-blast.go
- src/core/slowloris/slowloris.go
- src/jobs/base.go
- src/jobs/dnsblast.go
- src/jobs/http.go
- src/jobs/packetgen.go
- src/jobs/rawnet.go
- src/jobs/slowloris.go
- src/runner/runner.go
- src/utils/metrics/prometheus.go
Added client id to prom metrics because push gateways seem to not accumulate values from different clients
- Platform:
```text
logs
```
> add client id to prom metrics for distincion

- src/runner/runner.go
Make network logging more human-readable and understandable.
- Add tabbed alignment;
- Use Megabytes and Percent as metric
- Visually indent stats message.
Minor visual quality-of-life improvement for end-user
Tested on one local development machine.
WTR:
1. Run the app. 
2. Wait for usual message update timing after attack targets were written down.
3. Look at the terminal.
- Release version: [937ec0f](https://github.com/Arriven/db1000n/commit/937ec0fa1055c38d2f97436359f752fa316e33aa) 
- Platform: Windows x64
```
!Атака проводиться успішно! Руський воєнний корабль іди нахуй!
!Attack is successful! Russian warship, go fuck yourself!
---------Traffic stats---------
[     Generated ] 0.70 MB | 733382 bytes
[      Received ] 0.06 MB |  67398 bytes
[ Response rate ]  9.2% …
```
> human-readable client-side network stats logging

- main.go
- src/core/dnsblast/dns-blast.go
- src/core/slowloris/slowloris.go
- src/jobs/http.go
- src/jobs/rawnet.go
- src/runner/runner.go
- src/utils/countrychecker.go
- src/utils/metrics/prometheus.go
- Pass ClientID as const label for Prometheus
- Return country name from CheckCountry function
- Add country name to Prometheus metrics
This is useful if you're using Prometheus / Grafana to monitor overall performance.
> Return country name from CheckCountry and send to Prometheus

- config/examples/advanced/packetgen.yaml
- src/core/packetgen/serialization.go
- src/core/packetgen/serialization_test.go
- src/utils/templates/network.go
- src/utils/templates/templates.go
Some automated testing for packetgen
- Platform:
```text
logs
```
> Packetgen tests

- Dockerfile
- main.go
- src/jobs/base.go
- src/runner/runner.go
- testconfig.json
Use job filters instead of separate advanced config
Fixes #341 
- Platform:
```text
logs
```
> Use filters instead of separate advanced config

- ansible/linux/setup.yaml
- terraform/gcp_expressvpn/main.tf
added Docker flag --pull=always in order to automatically fetch new builds
- Release version: latest
- Platform: linux
```text
2022/03/19 09:21:09.579555 config.go:40: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.adv.json"
2022/03/19 09:21:09.579584 runner.go:80: The config has not changed. Keep calm and carry on!
!Атака проводиться успішно! Руський воєнний корабль іди нахуй!
!Attack is successful! Russian warship, go fuck yourself!
---------Traffic stats---------
[     Generated ] 64.79 MB | 67936815 bytes
[      Received ]  0.99 MB |  1039750 bytes
[ Response rate ]   1.5%
-------------------------------
2022/03/19 09:22:09.057885 config.go:40: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTe …
```
> docker pull always added

- src/core/packetgen/payload.go
Added dns package building 
Fixes # (issue) https://github.com/Arriven/db1000n/issues/49
- Platform:
```text
logs
```
> feat: add dns config

- main.go
- src/jobs/base.go
- src/jobs/http.go
- src/utils/templates/templates.go
- testconfig.yaml
Some proxylist cleanup
- Platform:
```text
logs
```
> Proxylist refactoring

- main.go
- src/utils/templates/encoding.go
- src/utils/templates/network.go
- src/utils/templates/templates.go
- src/utils/utils.go
- testconfig.yaml
copied json and yaml templates from helm. Also changed default config format to yaml as yaml is a superset of json and any valid json is also a valid yaml
- Platform:
```text
logs
```
> Template functions

- go.mod
- src/core/slowloris/slowloris.go
- src/jobs/slowloris.go
Added socks5 support to slowloris
WIP #279 
- Platform:
```text
logs
```
> added socks5 proxies support to slowloris

- src/core/http/http.go
- src/core/packetgen/packetgen.go
- src/jobs/rawnet.go
- src/utils/metrics/metrics.go
Track common protocol header sizes in rawnet jobs for better visibility (it's approximate but better than nothing)
Fix #12 
- Platform:
```text
logs
```
> Improve traffic tracking

- docs/faq.md
I think what you want to say is "primitive jobs are less resource intensive" or "more resource-efficient". The latter sounds wrong, so I'm going with the first one.
> Update command line description

- .github/CODEOWNERS
- .gitignore
- terraform/digital_ocean/README.md
- terraform/heroku/README.md
- terraform/heroku/terraform.tfvars
- terraform/hetzner_cloud/README.md
- terraform/hetzner_cloud/main.tf
- terraform/hetzner_cloud/provider.tf
- terraform/hetzner_cloud/terraform.tfvars
- terraform/hetzner_cloud/user_data.yml
- terraform/hetzner_cloud/variables.tf
- Support for Hetzner Cloud added
- Heroku cloud tested and updated app version
- Small fixes
Heroku terraform output:
```
$ terraform apply -var "email=${EMAIL}" -var "api_key=${API_KEY}"
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "heroku_app" "app" {
+ acm                   = (known after apply)
+ all_config_vars       = (sensitive value)
+ buildpacks            = [
+ "heroku/go",
]
+ config_vars           = {
+ "GOVERSION" = "1.17"
}
+ git_url               = (known after apply)
+ heroku_hostname       = (known after apply)
+ id                    = (known after apply)
+ internal_routing      = (known after apply)
+ name …
```
> Hetzner Cloud support

- docs/index.md
- docs/index.uk.md
> Mention --network host in the docs.

- examples/docker/static-docker-compose.yml
> docker compose updater mode fix

- terraform/vultr/README.md
- terraform/vultr/main.tf
- terraform/vultr/outputs.tf
- terraform/vultr/scripts/deploy.sh
- terraform/vultr/variable.tf
Added terraform configuration for Vultr.
Default config:
- Docker Ubuntu 20.04
- Seoul, South Korea
- 1 cpu 1 gb ram
- cronjob for periodic container restart
> Added terraform for Vultr

- terraform/aws/eks-cluster/data.tf
- terraform/aws/eks-cluster/main.tf
- terraform/aws/eks-cluster/modules/eks-cluster/data.tf
- terraform/aws/eks-cluster/modules/eks-cluster/main.tf
- terraform/aws/eks-cluster/modules/eks-cluster/outputs.tf
- terraform/aws/eks-cluster/modules/eks-cluster/variables.tf
- terraform/aws/eks-cluster/modules/eks-nodes/data.tf
- terraform/aws/eks-cluster/modules/eks-nodes/main.tf
- terraform/aws/eks-cluster/modules/eks-nodes/outputs.tf
- terraform/aws/eks-cluster/modules/eks-nodes/variables.tf
- terraform/aws/eks-cluster/modules/kubernetes/data.tf
- terraform/aws/eks-cluster/modules/kubernetes/main.tf
- terraform/aws/eks-cluster/modules/kubernetes/providers.tf
- terraform/aws/eks-cluster/modules/kubernetes/variables.tf
- terraform/aws/eks-cluster/modules/network/data.tf
- terraform/aws/eks-cluster/modules/network/main.tf
- terraform/aws/eks-cluster/modules/network/outputs.tf
- terraform/aws/eks-cluster/modules/network/variables.tf
- terraform/aws/eks-cluster/outputs.tf
- terraform/aws/eks-cluster/providers.tf
- terraform/aws/eks-cluster/scripts/node-user-data.sh
- terraform/aws/eks-cluster/variables.tf
- terraform/aws/eks-cluster/versions.tf
This implementation allows to deploy AWS EKS multi-az cluster and and it's infrastructure including VPC, subnets and cluster autoscaler.
- Platform: AWS
> AWS EKS cluster autoscaler implementation

- terraform/azure/README.md
- terraform/azure/variables.tf
Fix README for terraform azure
> Fix azure neutral name readme

- src/job/config/config.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Platform:
```text
logs
```
> only send lastmodified and etag if present

- ansible/aws/README.md
- ansible/aws/aws-provisioning.yaml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
1. Follow the manual to create the AWS account
2. Run ansible-playbook aws-provisioning.yaml
3. Ensure 2 EC2 instances are running
4. Log on to Linux instance and ensure db1000n container is running
5. Log on to Windows instance and ensure db1000n service is running
- Platform:
```text
logs
```
> AWS provisioning playbook and account creation manual

- src/utils/metrics/serve.go
This PR fixes an incorrect log printed when the service execution is canceled.
When stopping the service execution using Ctrl+C incorrect logs are no longer visible.
Before:
```text
^Cterminating
prometheus server	{"error": "http: Server closed"}
failure shutting down prometheus server	{"error": "context canceled"}
```
After:
```text
^Cterminating
```
- Platform:
```text
single http request     {"target": "https://gatemgmt.lamoda.ru/"}
single http request     {"target": "https://affiliates.lamoda.ru/partner/login"}
single http request     {"target": "https://www.biglion.ru/shops/kupons/"}
^Cterminating
➜  db1000n git:(log_fix) 
```
> Fixed log message for prometheus server

- terraform/hetzner_cloud/outputs.tf
> add hcloud_server output
