arriven/db1000n

- main.go
storing metrics on backend turned out to be more expensive that I thought, disabling for now
> Disable sending metrics by default

- README.md
tune readme to have easy copy-paste command for server run 
Also there is memory leak and therefore restart=always is required
> feat(doc): add docker commands for server run(for easy copy-paste)

- README.md
- run/run-openvpn.sh
In current implementation we have to replace `auth-user-pass` line with values that are provided `--env "OPENVPN_USERNAME="` and `--env "OPENVPN_PASSWORD="`.
This works fine if you have a setup where you are using a single VPN provider and multiple `.conf` files, typically representing different countries, and want to rotate between these configurations randomly.
This PR makes it possible to use different VPN providers at the same time by making `OPENVPN_USERNAME` and `OPENVPN_PASSWORD` optional and allowing user to specify credentials manually using `auth-user-pass credentials.txt` in each configuration file.
> Allow specifying username and password in config itself

- main.go
- src/utils/templates/templates.go
- added templating function `get_proxylist_by_url` to add ability to set separate proxies for each job
- added `p` flag to set generic list of proxies
config example
```
{
"type": "http",
"args": {
"method": "GET",
"path": "http://riabir.ru:443/",
"interval_ms": 2,
"client": {
"async": true,
"proxy_urls": "{{ get_proxylist_by_url \"https://test.com/proxylist.json\" }}"
}
}
},
```
closes #148
> added get proxies by url function and proxies url argument

- src/runner/runner.go
Sometimes you get EOF errors while trying to update job definitions:
```
[INFO]  2022/03/06 01:37:50 [INFO] Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json"
[WARN]  2022/03/06 01:37:50 [WARN] Failed to fetch config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json": Get "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json": unexpected EOF
```
Proposal is to fallback to `backupConfig` only when we get an error on the first start; otherwise use last known good configuration:
```
[INFO]  2022/03/06 01:37:50 [INFO] Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json"
[WARN]  2022/03/06 01:37:50 [WARN] …
```
> Use last known good config if new config can't be loaded

- src/jobs/slowloris.go
- src/slowloris/slowloris.go
Use stopChan to stop workers. 
Send number "stop" signals according to configured workers
> Slowloris - handle config reload

- src/dnsblast/README.md
- src/dnsblast/dns-blast.go
- src/dnsblast/dns-blast_test.go
- src/jobs/dnsblast.go
Job will query NS servers for this domain and send requests to all NS.
- Removed "port" option, since all target services uses standard ports
> - Change DNS job to accept domain name instead of NS IP.

- go.mod
- go.sum
- src/dnsblast/README.md
- src/dnsblast/dns-blast.go
- src/dnsblast/dns-blast_test.go
- src/jobs/dnsblast.go
- src/slowloris/slowloris.go
- testconfig.json
Refactor TCP over TLS connections to bypass SSL fingerprinting. This update brings a refactoring for two benchmarking jobs:
* SlowLoris
* DNSBlast
Research:
* https://habr.com/ru/post/596411/
* https://www.ietf.org/proceedings/91/slides/slides-91-dprive-5.pdf
* https://github.com/refraction-networking/utls
* https://ja3er.com/about.html
~~~
Note from the Author: Use only to test your own services, do not abuse services that you do not own! 
~~~
- [* ] New feature -> Randomized TLS handshake
- [*] Documentation update -> see `src/dnsblast/README.md`
- [*] TestBlast
> Refactor TCP-TLS connection to bypass filtering based on SSL fingerprinting

- docker-compose.yml
I've made a couple of changes to `wfg/docker-openvpn-client` docker image that were successfully merged into main branch and got released as `v2.1.0`:
https://github.com/wfg/docker-openvpn-client/pull/51
https://github.com/wfg/docker-openvpn-client/pull/52
This allows specifying a pattern to be used for `.conf` matching like this:
```yaml
ovpn_01:
image: ghcr.io/wfg/openvpn-client:2.1.0
cap_add:
- NET_ADMIN
security_opt:
- label:disable
restart: unless-stopped
volumes:
- /dev/net:/dev/net:z
- ./openvpn/:/data/vpn:z
sysctls:
- net.ipv6.conf.all.disable_ipv6=1
environment:
KILL_SWITCH: "on"
HTTP_PROXY: "off"
VPN_AUTH_SECRET: provider01_secret
VPN_CONFIG_PATTERN: provider01*.conf # this will match provider01_country01.conf, provider01_country02.conf etc
secrets:
- provider01_secret
```
Fixes …
> Add VPN_CONFIG_PATTERN to be able to do random VPN selection

- terraform/azure/bomblet/variables.tf
This default was mistakenly removed during docs refactoring.
Fixes #195 
> bring back default for attack env variable

- terraform/aws/main.tf
Small fix to prevent terraform state refreshing warning.
```
aws_autoscaling_group.example: Refreshing state... [id=ir_db1000n]
Note: Objects have changed outside of Terraform
Terraform detected the following changes made outside of Terraform since the last "terraform apply":
~ resource "aws_iam_role" "web_iam_role" {
~ assume_role_policy    = jsonencode(
~ {
~ Statement = [
~ {
~ Principal = {
~ Service = [
- "ec2.amazonaws.com",
"ssm.amazonaws.com",
+ "ec2.amazonaws.com",
]
}
},
]
}
)
id                    = "ir_db1000n_role"
name                  = "ir_db1000n_role"
tags                  = {}
}
Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these …
```
> [bug] aws terraform state fix

- src/packetgen/packetgen.go
One of prometheus metrics was gathering too much randomized attack data
Fixes #225 
> Don't use randomed values in packetgen metrics

- src/jobs/packetgen.go
- src/utils/templates/templates.go
Split parse and execute of templates in packetgen for performance (again, see switch to yaml as to when it was temporarily removed)
> Separate parse and execute mapstruct

- Makefile
- docs/prometheus.md
- src/metrics/prometheus.go
- src/runner/config/config.go
- src/utils/crypto.go
* TLS support for prometheus push exporter
* embed basic auth credentials and use authentication for prometheus push exporter
* optionally use embedded CA used to verify TLS connection with push gateways
* update Makefile with target to encrypt CA and embed to binary
* document prometheus exporter's configuration (look docs/prometheus.md)
* rename utils.DecryptConfig -> utils.Decrypt. Because it is used for all decryption
operations, not only for configuration files
- [+] New feature (non-breaking change which adds functionality)
- [+] Documentation update
- Up push gateway configured with TLS certificates and basic …
> Add basic auth and tls support for prometheus exporter

- src/packetgen/utils.go
It took me couple days to realize that most of the time when packetgen is bitching about and argument in sendmsg it doesn't like the ip containing leading 0. Tweaked random IP generation function to stop producing those value
Fixes #249 
* Release version: latest
* Platform: linux-amd64
> Fix random ip to not produce invalid IPs

- src/packetgen/packetgen.go
With all the latest changes ResolveHost was there for purely cosmetic reasons. Thanks @jdoe7865623 for noticing!
* Release version:
* Platform:
```text
logs
```
> remove redundant resolve host from packetgen.SendPacket

- src/packetgen/utils.go
- testconfig.json
force usage of ipv4 in `packetgen.ResolveHost`
- Platform:
```text
logs
```
> force resolve host to use ipv4

- src/runner/config/config.go
I found config updating process throws less errors when timeout is increased. Which makes sense since `db1000n` saturates your channel if you're using VPN.
> Increase HTTP timeout for fetching config to 20 seconds

- docker-compose.yml
This runs a command of your choice (`nslookup google.com`) every X seconds to verify that OpenVPN container still has an active VPN connection. If it doesn't, containers with `autoheal: true` label will be auto-restarted by [autoheal](https://github.com/willfarrell/docker-autoheal). While container is restarting, `db1000n` won't be able to access network so there should be no traffic leakage.
I've reviewed `autoheal` source code and it looks pretty reasonable.
Unfortunately accessing Docker socket requires running this container with privileged access.
```
timeout: 10s
interval: 30s
retries: 3
```
These values were selected by running a couple of experiments and they seem decent defaults but they might have to be adjusted to your particular situation.
Please delete options that are not …
> Add willfarrell/autoheal to docker-compose.yaml to restart OpenVPN containers

- terraform/azure/README.md
- terraform/azure/bomblet/main.tf
- terraform/azure/bomblet/variables.tf
- terraform/azure/main.tf
- terraform/azure/variables.tf
This PR adds an ability to explicitly specify db1000n flags in Azure terraform scripts. It might be very useful in case if custom config is required to be used.
Specify `attack_commands` variable in `terraform.tfvars`
``
attack_commands = ["/usr/src/app/main","-c=https://link_to_config"]
`
> Added an ability to specify app flags in azure terraform

- src/dnsblast/dns-blast.go
- src/dnsblast/dns-blast_test.go
- src/jobs/base.go
- src/jobs/dnsblast.go
- src/jobs/http.go
- src/jobs/packetgen.go
- src/jobs/rawnet.go
- src/jobs/slowloris.go
Use local function context in order to prevent metric writers being running after the job has crashed
> Fix goroutine leaks if job fails

- docs/configuration.md
Slowloris has been fixed couple days ago to support preliminary stop. Forgot to update configuration reference (TODO: update the configuration doc with all new jobs parameters)
> Remove warning about slowloris being unfinished

- Dockerfile
To be able to pass only args, instead of both command and args:
```
spec:
containers:
- name: db1000n
image: ghcr.io/arriven/db1000n:latest
args: ["-enable-self-update"]
```
> Use ENTRYPOINT instead of CMD

- docker-compose.yml
Added healthcheck and autoheal labels to every container
Think for `willfarrell/autoheal` container to work properly the `healthcheck` and `label` should be on every container. Currently If `ovpn_XX` container stops working and is restarted by autoheal, the `db1000n_XX` that depends on it will not have a functioning network and needs are restart also. (At least in my testing)
> Added healthcheck and autoheal labels

- src/runner/config/config.go
- src/runner/runner.go
This will rely on `Last-Modified / If-Modified-Since` headers to see if remote config has changed. If these headers aren't available, it will try to use `Etag / If-None-Match` as fallback. If those aren't available either it will simply try to fetch whole file. This should result in less traffic to CDNs and will somewhat improve speed of fetching configs (to an extent).
This also fixes a bug where encrypted config was compared with decrypted `rawConfig`.
Tested by running locally and in Docker.
```text
01:39:37.373336 runner.go:155: The app has generated approximately 81347432 bytes of traffic
01:39:37.373605 runner.go:158: Of which for 37927 bytes we received some response from the target
01:39:37.566090 config.go:98: Received HTTP 304 Not Modified
01:39:37.566116 config.go:58: Loading …
```
> Refactor how configs are fetched

- src/runner/config/config.go
Check for absolute path in `config.fetchSingle`
Fixes #318 
> fix absolute path handling for configs

- src/utils/templates/templates.go
now proxies urls can be provided not only as json array but as plain text delimited with newline(`\n`)
Fixes #282
Run `go run main.go -c https://pastebin.com/raw/2WX69bsd`
> feat: added plain text proxy list parsing

- terraform/aws/main.tf
removed section from AWS terrafrom that could make deployment so long
Fixes #244
- go to ./terraform/aws directory
- run `terraform init`
- run `terraform apply -var-file="ireland.tfvars"`
> fix: terrafrom aws simplified

- docker-compose.yml
- main.go
- src/utils/countrychecker.go
- src/utils/utils.go
I'm still trying to figure out how to make Docker VPN setup be more stable, hopefully this is step in right direction.
IP/Country check will be performed before starting any jobs. This is slight departure from current code but it shouldn't be a breaking change as options are turned off by default.
Setting `--country-list` parameter allows to specify comma-separated list of countries to check IP against
Setting `--strict-country-check` parameter will result in app exiting if
- IP matches one of the countries in the list above OR
- IP cannot be determined
Since `db1000n` container starts right after VPN container starts, there's little no guarantee that VPN tunnel is actually established. This often results in app not being able to download configuration and default to built-in …
> Add --strict-country-check and --country-list command line parameters

- src/runner/config/config.go
Seems like logging `Received HTTP 304 Not Modified` might be confusing. It's also somewhat redundant since app will log `The config has not changed. Keep calm and carry on!` anyway.
Related to https://github.com/Arriven/db1000n/issues/327
> Remove '304 Not Modified' to not cause confusion

- Dockerfile
- docker-compose.yml
- main.go
- src/runner/config/config.go
- src/runner/runner.go
- src/utils/updater/updater.go
This is mostly useful if you're running `db1000n` with docker-compose with VPN container. In this case you're likely to receive errors or time-outs while trying to update config file due to the fact that VPN connection is already highly saturated. Typically it looks like this:
```
runner.go:154: The app has generated approximately ... bytes of traffic
runner.go:157: Of which for ... bytes we received some response from the target
config.go:55: Failed to fetch config from "https://raw.github.com/.../config.json": Get unexpected EOF
config.go:66: Could not load new config, proceeding with the last known good one
config.go:148: The config has not changed. Keep calm and carry on!
```
Updater mode is a simple loop that will try fetching config file from remote server and store it in shared …
> Add "updater mode"

- src/utils/metrics/prometheus.go
use empty cert pool in prom if system one is unavailable (like on windows)
- Platform:
```text
logs
```
> create empty cert pool if system one is unavailabe

- config/examples/advanced/packetgen.yaml
- src/core/packetgen/application.go
- src/core/packetgen/connection.go
- src/core/packetgen/link.go
- src/core/packetgen/network.go
- src/core/packetgen/packetgen.go
- src/core/packetgen/serialization.go
- src/core/packetgen/transport.go
- src/jobs/packetgen.go
- src/utils/utils.go
Previous packetgen implementation was quite hard to extend with new protocols. This one should be a lot more modular. This refactoring breaks previous packetgen configs but we don't use it in the current default config yet so I'm making a decision to cut not support it
Useful for #49 and #360 
> refactor packetgen (WIP)

- src/core/http/http.go
- src/jobs/http.go
- src/jobs/rawnet.go
- src/utils/proxy.go
- src/utils/utils.go
Allow using socks5 proxy in tcp jobs. Inspired by #381
WIP #279 
- Platform:
```text
logs
```
> allow using socks5 proxy in tcp jobs

- src/core/packetgen/serialization_test.go
Added test for `serialiation_test.go`, included check payload for ipv4/ipv6 packets and different payload string and int.
test cases
@Arriven just a question, is this ok to use some package for test like assert to avoid linter issues with cyclomatic complexity. I believe soon there is will be many type of packages and payload. So test cases will be a bit tricky to maintain.
> Added few cases for serialization_test

- main.go
- src/utils/ota/ota.go
- src/utils/ota/restart.go
- src/utils/ota/restart_windows.go
- src/utils/ota/shared.go
- src/utils/ota/shared_test.go
(Codename: `Glory to Those who protect the Land`)
This patch brings the restart the option for the DB1000N on the OS with non-boring wallpapers.
Take care and stay safe, folks!
1. https://github.com/golang/go/issues/29841
2. https://superuser.com/a/1656458
> DB1000N | Add support for the restart option after the auto-update for the Windows OS

- config/examples/http-host.yaml
- src/core/http/http.go
- src/jobs/http.go
Allow sending http traffic to a predefined host different from a url one to prevent dns re-targeting
- Platform:
```text
logs
```
> allow sending http flood to static host

- terraform/aws/main.tf
- terraform/aws/variables.tf
Added arm instance type and ami for the aws terraform configuration.
arm instance is more performant and cheaper than regular non graviton instances.
> terraform: Added arm support for aws

- terraform/aws/ireland.tfvars
- terraform/aws/main.tf
- terraform/aws/tor-proxy/tor-proxy.tf
- terraform/aws/variables.tf
This is more a basis for discussion than a serious proposal to merge. I'm happy to take suggestions, I am not a tor expert so there may be much that can be improved, eg using some other existing tor proxy setup, or not using one at all. 
The goal is to obfuscate the origin IPs and keep them changing, and to create a simple way of creating a db1000n installation with proxy, in AWS. It's immediate benefit is that it seems to work, as far as I can tell.
Notes:
- var.name is changed as NLBs don't support underscores in their names
- the db1000n servers will need to be restarted if the NLB is recreated. Is it possible to change the db1000n proxy config without restarting?
- there is a var.zones variable that allows you to configure the number of availability zones - defaults to 2. LBs require …
> [DRAFT] Add load balanced tor proxy to AWS terraform config

- src/runner/runner.go
Ру́ський (прикметник) (давньоруськ. руськии, пол. ruski) — в українській мові такий, що відноситься до часів Русі або до її населення — русічи їхніх нащадків — українців. Слово руський не слід плутати з рос. русский, тобто росіянин.
> Руський - це український. Варто про це пам'ятати.

- terraform/azure/README.md
- terraform/azure/bomblet/variables.tf
- terraform/azure/main.tf
- terraform/azure/variables.tf
Update the terraform config for Azure:
- stop overriding container's `commands` (the default config URL was wrong);
- propagate `environment_variables` and set ``ENABLE_PRIMITIVE: false``.
Now terraform deployment for Azure can be launched right away without the need of configuration update, and disables primitive jobs by default (complementing https://github.com/Arriven/db1000n/pull/428)
To test `ENABLE_PRIMITIVE=false`:
- Release version: 0.8.4
- Platform: Azure container instances
> Update Azure terraform config

- src/runner/config/updater.go
https://github.com/Arriven/db1000n/commit/750f6bdf27af85a19427cc0bf63d0e23b157a384#diff-010176c2ca9e3ceeacb9d76da1fca2f2df823fd20df0bb68d2a773616e063de5 introduced a bug in updater where it will exit upon successful file download. Previously it would only exit if there's an issue while trying to download the file.
It's easy to verify even without using Docker by running `go run main.go --updater-mode=true` on v0.8.6
Fixes https://github.com/Arriven/db1000n/issues/439
> Fix updater exiting early

- docker-compose.yml
* Updating example config path as they changed if the Docker image is built with `ko`
* Removing healthcheck example commands as they won't work for `ko` images anymore
Fixes https://github.com/Arriven/db1000n/issues/439
> Updater docker-compose.yaml

- src/jobs/base.go
- src/jobs/http.go
- src/jobs/rawnet.go
- src/utils/backoff.go
- src/utils/countrychecker.go
Introduce exponential backoff for http and tcp jobs loop to prevent cpu overload on failures
Fixes #448 
> exponential backoff implementation

- terraform/azure/variables.tf
Make azure terraform names more neutral to avoid banning
- Platform:
```text
logs
```
> neutral name for terraform azure

- install.sh
For some devices (like PinePhone), OS_ARCH is aarch64, which is the same as arm64.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Platform:
```text
logs
```
> Added aarch64 architecture

- main.go
the most human readable format for those who only look at the output in a terminal
With the recent switch to `zap` as the used logger it became much harder to just look at terminal's output. If you just run it manually and the output is for reading rather than logging, using `-log-format simple` makes the output much more bearable.
By running and looking at the output in a terminal.
- Release version: latest main branch (v0.8.30 is the latest current release)
Output sample (real values crossed out)
```text
db1000n % ./db1000n -log-format simple
running db1000n {"version": "v0.8.30", "pid": 84370}
checking IP address,    {"iter": 1}
error fetching location info    {"error": "Get \"https://sample/\": context deadline exceeded"} …
```
> Add a new flag `-log-format` and a `simple` format

- src/utils/metrics/metrics.go
so the whole report goes as one log entry with a JSON object for each target
This might be helpful for logging and assessing to have the whole summary report as one entry. Though arguably it makes it even less readable in terminal's output, and I tried to improve that with pr #517. I tried to make `zap` pretty print this huge JSON report object (for the case when `-log-format simple` from #517), but it was way too complicated for such a simple feature. Though it might still be possible.
What do you guys think? Could this be helpful?
Potentially somebody could rely on the current summary format, but with so many swift changes and the recent move to `zap` - I doubt it.
By running and looking at the output in a terminal.
- Release version: latest main branch (v0.8.30 is the latest current …
> Combine metrics summary into one object

- main.go
- src/job/http.go
- src/job/runner.go
- src/utils/metrics/accumulator.go
- src/utils/metrics/metrics.go
- src/utils/metrics/reporter.go
- src/utils/metrics/stats.go
I want to improve it further to show a pretty summary like before. For this I split `Reporter` into several implementations - for zap and console.
Also `simple` output format is made default now.
It's a work in progress - I intend to split `mectrics.go` into several files. But I hope it gives a preview of what's coming if somebody touches same files.
**P.S.** I intend to finish this somewhere around today's evening.
if some scripts or bots use json as default now - we need to update those before releasing - the default becomes simple.
By running and looking at the output in a terminal.
- Release version: latest main branch (v0.8.31 is the latest current release)
Output sample (real values crossed out, truncated for shorter text, alignment in console is better)
```text …
```
> Simple output improvements (also make simple output format default)

- src/utils/metrics/reporter.go
- src/utils/metrics/stats.go
When run with simple output format the table reported doubled total stats. There was an additional loop for totals which I didn't notice when copied table's formatter implementation. Also I shrank the table implementation a bit.
By running in a terminal
- Release version: latest dev (current release version is .33)
> Fix double total stats reported in table simple output

- main.go
instead of default epoch floating time
This format should be more familiar for users. Why not ISO8601 - to my taste RFC3339 is a tad more readable. Although both formats are almost interchangeable.
It  changes the existing `console` log format, some users might rely on epoch time.
Ran in my terminal, saw the output.
- Release version: latest main's top (latest release is .33)
After the change:
```text
2022-05-08T15:56:23+03:00       info    job/http.go:70  single http request     {"target": "https://sample"}
2022-05-08T15:56:23+03:00       info    job/http.go:70  single http request     {"target": "https://sample"}
```
> Switch console log time format to RFC3339

- src/utils/metrics/reporter.go
Writing letter-by-letter is very inefficient.
On kinda slow machines, the whole table was printing in like 10 seconds word by word.
This commit prevents these write calls
because now, everything is added to a 4096-byte buffer and flushed in the end.
Multiple 1-byte write syscalls were made without buffering.
Added buffering in metrics reporter.
> perf: add buffering in metrics table reporter

- main.go
- src/utils/metrics/metrics.go
- src/utils/metrics/reporter.go
Adds a cmd line parameter `-less-stats` to group all target stats by protocols. Currently the list of stats could be very long and it's not always convenient to observe.
Maybe "fewer" would be more grammatical, but I guess "less" is kinda more conventional for text and more widespread (think of `less` utility).
Running in a terminal and observing the output.
- Release version: latest main (latest release is 0.9.8)
After the change with `-less-stats` supplied:
```text
--- Traffic stats ---
| Target | Requests attempted | Requests sent | Responses received | Data sent |
|   http |               8707 |          2491 |               2491 |   0.41 MB |
|  https |               8225 |          1051 |               1051 |   0.17 MB |
|    tcp |              37952 | …
```
> Add `-less-stats` cmd param to group targets by protocols

- main.go
- src/utils/utils.go
Added flag for periodic GC invocation  to reduce overall memory consuption in pooling scenarios (db1000nx100)
manually tested
> Added flag for periodic GC invocation 
